### ISSUE TITLE
Unnecessary requirements in IMap

### ISSUE THREAD

**Issue by darrellp** [hybrid1969/RogueSharp#1]
There are many methods in IMap which can be implemented in terms of other IMAP methods.  These can be implemented as IMap extension methods and removed from IMap so the implementors are freed from having to implement those methods and instead they come "free" as a result of implementing the other methods.  I've done this in a fork of my own and would be happy to provide the results.  I'd like to collaborate on this project.  There are several issues I'd like to address in a spirit of friendly collaboration.

**Comment by hybrid1969** [comment]
Sorry for the later response as been swamped recently.

Yes I would be interested to see your refinements and collaborate as I had intended to look at this fully with the intention of expanding and improving it, in the near future.

**Comment by darrellp** [comment]
Ah - sorry.  Not trying to be flip, but eventually I figured you weren't interested so tossed my changes and started working on my own engine at CSRogue.  The main thing I think you might want to look into is to make extension methods on your interfaces.  Right now you've got a bunch of methods in your interfaces which have to be implemented by boilerplate code in every implementation of the interface (sorry - don't recall verbatim examples).  These can all be replaced by extension methods on the interfaces which contain essentially that boilerplate code and then you don't have to implement these redundant methods in every concrete implementation.  Should make it much easier for implementors.  Again, sorry for moving on.  Good luck on the project!  I'm really excited about Roguelikes and love to see lots of people in working on them!  

P.S.  Actually, does my fork still exist in Github somewhere?  I'm pretty new to Github and so maybe it does and I just don't know about it.  If so, you could find my changes there.
